import Foundation
public enum EnrollmentStatusType : Int{
    case SEND_TO_HQ_INITIATED = 0
    case SEND_TO_BLOB_INITIATED = 1
    case SAVED_BLOB_TO_KEYCHAIN_SUCCESSFUL = 2
    case SAVED_BLOB_TO_KEYCHAIN_FAILURE = 3
    case SAVED_AZURE_PAYLOAD_TO_KEYCHAIN_SUCCESSFUL = 4
    case SAVED_AZURE_PAYLOAD_TO_KEYCHAIN_FAILURE = 5
    case SAVED_BLOB_TO_DATABASE_SUCCESSFUL = 6
    case SAVED_BLOB_TO_DATABASE_FAILURE = 7
    case SAVED_AZURE_PAYLOAD_TO_DATABASE_SUCCESSFUL = 8
    case SAVED_AZURE_PAYLOAD_TO_DATABASE_FAILURE = 9
    case SENT_TO_AZURE_FUNCTION_SUCCESSFUL = 10
    case SENT_TO_AZURE_FUNCTION_FAILURE = 11
    case SENT_TO_BLOB_FUNCTION_SUCCESSFUL = 12
    case SENT_TO_BLOB_FUNCTION_FAILURE = 13
    case CANCELLED = 15
}
